#!/bin/bash
RVM_GEMSET=$(cat .ruby-version .ruby-gemset | tr "\n" "@" | sed 's/@$//')
echo "using ${RVM_GEMSET} gemset"

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"
[[ -s "/usr/local/rvm/scripts/rvm" ]] && . "/usr/local/rvm/scripts/rvm"

rvm --create --install use $RVM_GEMSET

export BUNDLE_GEMFILE=$(pwd)/Gemfile

which bundle | grep ${RVM_GEMSET} >/dev/null || gem install bundler --no-rdoc --no-ri

bundle check > /dev/null || bundle install

test=$1

echo "running $test test"

FACTER_hiera_root_dir=$(pwd)/hiera bundle exec puppet apply --modulepath ./modules --hiera_config hiera/hiera.yaml manifests/$test.pp
